### ISSUE TITLE
Docker for development environment?

### ISSUE THREAD

**Issue by baohx2000** [ElamGarak/EyeChart#10]
Yes, it's something new to learn if you haven't already, but for development, it makes life much easier. If you're using windows, maybe not so much (unless you're on windows "pro").

Docker containers will eat up much less room than VMs. At my job I usually have about 50 docker containers running on my laptop, covering ~15 microsrevices, 2 frontends, and 4 or 5 types of databases.

Granted, this sounds like a one service + one database application, but there's something to be said for a consistent development environment.

**Comment by baohx2000** [comment]
This is not to say you have to use docker in production, but being able to run a simple "start.sh" script to bring up your db and application(s) without worrying about vagrant or memory/port constraints if you're running other stuff locally is pretty nice.

**Comment by ElamGarak** [comment]
If I understand what you are saying, I think I have gotten around that by using xammp and gitbash.  I have been able to host locally and run sh scripts.  Apples to apples?

**Comment by baohx2000** [comment]
That's fine, as long as it's expected that other developers on the project to have to do the same. xampp only exists as a VM for OSX (I assume you're running on Windows?) so i'd have to install something to handle all that.  Running docker, you'd be running an actual linux environment, very close to what you'd be running in production so it's unlikely you'd run into weird OS compatibility issues, and adding something like redis or elasticsearch to the mix would be trivial.  Setup & install could even be handled via docker containers so you'd never have to get php/composer/etc running on your host system, and again, it'd be pretty much guaranteed to be a consistent environment no matter who's running it.  Plus, if you decide you'd rather separate front & back end by doing a single-page app using React or Vue, it's just a matter of adding a nodejs container to start working with.

I see an `.htaccess` so I assume I'd have to run apache + mod_php to get this thing going. Personally haven't run apache in years, but as long as I can have some config files, that's fine.
There is also some `web.config` file that I have no idea about.
Not sure if there are db migrations to run, or how to do so? Is a specific database expected to already be created?

A `SETUP.md` might be nice to help with setting up the environment initially, or add instructions to `README.md`.

Again, just suggestions as a "new dev to the project".

**Comment by ElamGarak** [comment]
Love the suggestions!  :)

In answer to the questions... 

`.htaccess` is leftover garbage from the old code base.  Thanks for pointing that out, I will remove.

`web.config` much the same.  But in time this is going to be plugged into a SQLServer database which I think uses that.  (or it could be ISS, I don't remember now)  Again though, I can remove it for now as it is useless.

As for dockers, excellent points.  For now though, I am the only developer on this.  Should this ever become a collaboration then I am with you on docker.  I have never used it but have played around with it in PHPStorm.  Sounds as if you are the guru I need to show me harmony with it lol :)

**Comment by ElamGarak** [comment]
@baohx2000 I went ahead and closed this.  I was able to remove the web.conf.  However when I removed the .htaccess, it blew up on me.  I am going to leave it for now but I suspect you and I will be having a few beers soon in front of my computer!
