### ISSUE TITLE
Add vendor to .gitignore; add composer.json; add license; delete and redo github repository

### ISSUE THREAD

**Issue by clarkphp** [ElamGarak/EyeChart#6]
One Issue to Rule them All !

It is generally undesirable to track changes in the vendor folder. Reference:
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

It is possible to remove and untrack files that had been originally tracked, using `git rm --cached` but perhaps best to start a clean GitHub repo, and remove all evidence there ever was a vendor folder committed.

It is possible to tell git to create a new repository from an existing one, without carrying over the history, but I don't recall how to do that at the moment.  Shell script below for manually achieving similar.

1. **Remove repository on GitHub**. Yep, delete the fact we were ever here.
2. **Add .gitignore file** that includes this line:
`vendor/`

In fact, you probably want something more like this, depending on what you know about the project's future (if composer.phar is not in the project root, remove that line). Also exclude IDE artifacts.
```
composer.phar
vendor/

config/autoload/*.local.php

data/logs/
data/cache/
data/sessions/
data/tmp/
temp/

```

3. Make sure to **not ignore composer.json**. It should be committed and tracked in the repo.
4. Add LICENSE.md with an appropriate license. This can be hard to choose, but a library is by default "All Rights Reserved" and no one with any legal sanity will use a library in their code without explicit permission to do so.  This is the reason a few of my personal projects are not yet on GitHub, BitBucket, or GitLab.
https://opensource.guide/legal/
https://choosealicense.com/licenses/
https://opensource.org/licenses

This is a script to create a new fresh repository, hiding early sins. You can modify URLs for github, or use as a manual checklist. You'll lose history up to this point, and if that's important, but it's early days in the project.  If history is important, we'll take a different approach.

``` bash
# stop on first error. Not best practice, but okay here
set -e

# Settings
user=xxx
pass=xxx
dir=xxx
repo_src=xxx
repo_trg=xxx
src_branch=xxx

# need to edit for github (and I use SSH key, not password)
repo_base_url=https://$user:$pass@bitbucket.org/$user
repo_src_url=$repo_base_url/$repo_src.git
repo_trg_url=$repo_base_url/$repo_trg.git

echo "Clone Source..."
git clone -b $src_branch $repo_src_url $dir

echo "change directory"
cd ./$dir

echo "Remove local git repo"
rm -rf .git

echo "Init new git repo"
git init
git add .
git commit -m "Initial Commit"
git remote add origin $repo_trg_url

echo "Push..."
git push -u origin master

```

**Comment by ElamGarak** [comment]
@clarkphp Thanks!  @baohx2000 had advised me to do something along these lines earlier.  I'm thinking I may need to reorder my priorities and get vendor out of here lol.  I did a complete new repo against this last week so I am familiar with what you are saying with 'rewriting history'  (or rebooting into a parallel universe? lol.

I'll work on this next.

**Comment by ElamGarak** [comment]
@clarkphp I think I got this one done.  I had to use a different route than you gave me but the results are the same.  The history has been reset and vendor is gone.  Composer.json is in.  Do I also include composer.lock?  Please take a peek and let me know if all looks well.

**Comment by ElamGarak** [comment]
@clarkphp I'm going to close this pending your review.  I think I got everything in place you had suggested.

Thanks!
